### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by wincowgerDEV**
A few more things we can add to check_OpenSpecy that I think would break most of the functions if they weren't true.

### CODE REVIEW

**Comment by wincowgerDEV** [comment]
@zsteinmetz I think I want the `check_OpenSpecy` function to only return TRUE or FALSE plus warning messages. I am currently trying to implement it in the Open Specy app and its really difficult to catch warnings, messages, and errors and pass them to messages. Plus how we have it currently set up to return FALSE even if it is a message makes me think the primary use will to return the logical in for loops or other operations then get warnings if there are issues. Going to implement it now but let me know if you want me to revert if you think it should be structured differently.

**Comment by zsteinmetz** [comment]
> @zsteinmetz I think I want the `check_OpenSpecy` function to only return TRUE or FALSE plus warning messages. I am currently trying to implement it in the Open Specy app and its really difficult to catch warnings, messages, and errors and pass them to messages. Plus how we have it currently set up to return FALSE even if it is a message makes me think the primary use will to return the logical in for loops or other operations then get warnings if there are issues. Other thing that is nice about this is all the warning messages are printed so if someone has multiple things wrong they can fix them all at once. Going to implement it now but let me know if you want me to revert if you think it should be structured differently.

Sounds good to me :+1:

**Comment by zsteinmetz** [comment]
Should we go for v1.0.3 soon so that you can add those changes to the Shiny app?

**Comment by wincowgerDEV** [comment]
> Should we go for v1.0.3 soon so that you can add those changes to the Shiny app?

Yeah, I think I would like to go for more frequent deployment updates than previously, I think for the last two years we were stuck because we overhauled the framework so much didn't want to break everything for everyone but now all the changes are pretty minor. Would be nice to get these changes into the shiny app for sure.

**Pull request merged**
