### PR TITLE
Streamlined file sharing. 

### PR DESCRIPTION
**Pull request by wincowgerDEV**
This primarily add support for the new csv format described in https://github.com/wincowgerDEV/OpenSpecy-package/issues/160

Adds a new function for calculating the number of spectral points needed to fill a window with wavenumber specification. 
https://github.com/wincowgerDEV/OpenSpecy-package/commit/8f8dd470041c347214dbcfd5464d1d88595c2a29

Also adds a minor bug fix for duplicate column names when xy are used in the metadata. https://github.com/wincowgerDEV/OpenSpecy-package/commit/f4d55235258ab114bae5d5d42081bab37c4c5e57

And adds a new experimental function for interpreting the similarity between Open Specy objects: 
https://github.com/wincowgerDEV/OpenSpecy-package/commit/2c3cf9e6ee0ef51fa00f2e180d100762cfebbc2a

### CODE REVIEW

**Comment by wincowgerDEV** [comment]
@zsteinmetz this one has a few bug fixes and some new functionality, I got the check and tests all working and ready for your final review when you have time.

**Comment by zsteinmetz** [comment]
Hey @wincowgerDEV. Hope you're doing well! Thanks for keeping the ball rolling. I'll have a look as soon as I can and prepare a new CRAN submission afterwards ..

**Comment by wincowgerDEV** [comment]
> Hey @wincowgerDEV. Hope you're doing well! Thanks for keeping the ball rolling. I'll have a look as soon as I can and prepare a new CRAN submission afterwards ..

Hope you are doing well too man! No worries on the timing, these are mostly nice to have. Lots of new people have been using the package which is super exciting!

**Comment by wincowgerDEV** [comment]
@zsteinmetz I know we talked about this a while back but I think it might be time to bring the sgolay filter function in front the signal package. This will allow us to customize it and I think they have a subfunction in it that interpolates values near the tails. We could really use that to improve the new conform_spec and smooth_spec methods I added. Let me know what you think and if you have any ideas after testing things out.

**Comment by wincowgerDEV** [comment]
Added all this and a bag of chips: https://github.com/wincowgerDEV/OpenSpecy-package/issues/165

I think the last thing to do on this @zsteinmetz is probably add a few specific tests and example routines for the new spatial smoother functions. 

Hmm, somehow it is failing on this server but not on my personal comp, will check that too.

**Comment by wincowgerDEV** [comment]
Got the error fixed but still one warning about global variables to fix.

**Comment by wincowgerDEV** [comment]
@zsteinmetz, I think I have things stable again, everything is always a work in progress but would love to get these new features out soon so that we can roll them out on the web site. I know you are super busy but would greatly appreciate if you have a chance to review these updates before we push to cran.

**Comment by wincowgerDEV** [comment]
Going to merge to main so that others can start using while we prep for cran.

**Pull request merged**
