### PR TITLE
Cran fixes

### PR DESCRIPTION
**Pull request by wincowgerDEV**
Opening this to start a discussion

### CODE REVIEW

**Comment by wincowgerDEV** [comment]
@zsteinmetz, went through and ignored some of the tests and examples that cran was upset about. Also tried to speed up the vignette.

**Comment by zsteinmetz** [comment]
Hey @wincowgerDEV, I already reduced the number of examples before. Let's try another submission with the remaining ones before excluding them completely. `dontrun` examples are often neglected because everybody thinks they're wrong by example.

**Comment by wincowgerDEV** [comment]
Sounds good!

**Comment by zsteinmetz** [comment]
I ran some additional tests. Timings look better now. Preparing 1.0.1 ...

**Pull request merged**
