### PR TITLE
Flip xy coordinates in ENVI files

### LINKED ISSUE #150: [Bug]: XY coordinates flipped in maps
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

current

### Platform and OS Version

Windows

### Existing Issues

_No response_

### What happened?

The xy coordinates are flipped for me when I use read_any on my Thermo iN10 compared to what I see on the device. I am not sure if this is a cross platform issue or a platform specific issue so I am currently just posting this to see if other people are also having the bug and if they are we can easily swap them. 

### Steps to reproduce

1. Look at x y on hyperspectral imager during the acquisition and compare to the xy with read any and plotting with heatmap_spec

### Expected behavior

Same xy coordinates. 

### Attachments

_No response_

### Screenshots or Videos

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by zsteinmetz**
Fixes #150

### CODE REVIEW

**Comment by zsteinmetz** [comment]
@wincowgerDEV, could you maybe have a second look if the coordinates are correct now? No worries, builds are failing only because I haven't updated the tests yet ..

**Review by wincowgerDEV — COMMENTED** [review]
Code updates look good to me with a quick look but the heatmap output for sig_noise of the tiny map should reveal a blob in the center. 

```r
test <- read_any(read_extdata("CA_tiny_map.zip"))

heatmap_spec(test, z = sig_noise(test, metric = "sig_times_noise"))
```
This is what it looks like right now:
image

This is what it used to look like: 
image

The two should really just be mirror images of one another but it looks like the alignment is off somehow.

**Comment by wincowgerDEV** [comment]
Not quite sure how to write a test for this but I think I got it figured out, the `dcast` needed to be updated too. Committing soon. 
image

**Comment by wincowgerDEV** [comment]
I think we got it now.

**Comment by zsteinmetz** [comment]
Thanks, Win!

**Pull request merged**
