### PR TITLE
Streamlining identification

### PR DESCRIPTION
**Pull request by wincowgerDEV**
Right now I think identification is a little convoluted because it always requires that you use preprocessing first to conform the spectra. I want conformation to be a part of the match_spec function too. This configuration will allow us to speed up the processing routine in the app by bypassing the conformation step until we do the match. In many cases, code workflows will also be more succinct because the match_spec function can be used alone. I want to make a new test to make sure that this update conforms to the alternative routine and add this logic into the tutorials.

### CODE REVIEW

**Comment by wincowgerDEV** [comment]
Also adding fix for https://github.com/wincowgerDEV/OpenSpecy-package/issues/154

**Comment by wincowgerDEV** [comment]
@zsteinmetz, I am pretty happy with this PR, if you have a chance to review and sign off too, that would be great! Trying to Keep PRs relatively small and manageable so we don't end up having that monster PR like the big release one again.

**Comment by zsteinmetz** [comment]
> Trying to Keep PRs relatively small and manageable so we don't end up having that monster PR like the big release one again.

Totally agree!

**Comment by wincowgerDEV** [comment]
@zsteinmetz Hope you are doing well! Just pinging you again, I got these changes implemented now in the shiny app. If we can push this update to CRAN it will allow me to more easily streamline the update there.

**Comment by zsteinmetz** [comment]
So sorry! It's been quite stressful lately. I'll look into it first thing next week.

**Comment by wincowgerDEV** [comment]
Sorry to hear you've been stressed out lately man please let me know if I
can help in any way! Really appreciate you sending this through.

**Pull request merged**
