### PR TITLE
Various bug fixes

### LINKED ISSUE #144: [Feature]: add ctb
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

person(given = "Philipp",
             family = "Baumann",
             email = "info@spectral-cockpit.space",
             role = c("ctb"),
             comment = c(ORCID = "0000-0002-3194-8975")),

### Problem

- there is no problem

### Proposed Solution

you can add me as ctb :-) cheers

### Alternatives Considered

no

### LINKED ISSUE #145: [Bug]: heatmap_spec(showlegend=TRUE)
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

_No response_

### Platform and OS Version

macOS 12.6.8 

### Existing Issues

_No response_

### What happened?

Hi,

I was trying to show the legend within the heatmap function using showlegend=TRUE but it does not show it. 

Thanks

### Steps to reproduce

1. heatmap_spec(spectral_map_p, sn = spectral_map_p$metadata$sig_noise, min_sn = 5, font = list(color = "#000000"), showlegend = TRUE, colorscale = "Blues", reversescale = TRUE, paper_bgcolor = "white") 
2. 
3.
...

### Expected behavior

To show the legend

### Attachments

_No response_

### Screenshots or Videos

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by wincowgerDEV**
Fixes a fatal error in `match_spec()` probably causing incorrect identifications. Also fixes #144 and fixes #145.

### CODE REVIEW

**Comment by wincowgerDEV** [comment]
@zsteinmetz, could we merge this one pretty soon and send it to CRAN? I discovered a fatal error in the match_spec function so people are likely getting incorrect identifications currently, and want to make sure we correct that soon. The error was causing the identities from the libraries to be scrambled. I ran the checks and there is one thing I still can't figure out, it says that an incorrect "}" is being used but I cannot find the offender.

**Comment by zsteinmetz** [comment]
I'll try to check the code asap and prepare a new submission.

**Comment by zsteinmetz** [comment]
@wincowgerDEV, have you got an email to accept the new CRAN submission?

**Comment by wincowgerDEV** [comment]
> @wincowgerDEV, have you got an email to confirm the new CRAN submission?

@zsteinmetz , yup, got it and accepted.

**Pull request merged**
